// used for testing purposes
let testCategories = [
    { id: 21, name: "Sports" },
    { id: 31, name: "Entertainment: Japanese Anime & Manga" },
    { id: 14, name: "Entertainment: Television" },
    { id: 20, name: "Mythology" },
    { id: 29, name: "Entertainment: Comics" },
    { id: 11, name: "Entertainment: Film" },
];

let testQuestions = [
    [
        {
            category: "Vehicles",
            type: "multiple",
            difficulty: "medium",
            question: "Which of the following countries has officially banned the civilian use of dash cams in cars?",
            correct_answer: "Austria",
            incorrect_answers: ["United States", "Czechia", "South Korea"],
        },
        {
            category: "Vehicles",
            type: "multiple",
            difficulty: "hard",
            question: "Volkswagen&#039;s legendary VR6 engine has cylinders positioned at what degree angle?",
            correct_answer: "15 Degree",
            incorrect_answers: ["30 Degree", "45 Degree", "90 Degree"],
        },
        {
            category: "Vehicles",
            type: "multiple",
            difficulty: "easy",
            question: "What is the name of Nissan&#039;s most popular electric car?",
            correct_answer: "Leaf",
            incorrect_answers: ["Tree", "Deer", "Roots"],
        },
        {
            category: "Vehicles",
            type: "multiple",
            difficulty: "hard",
            question: "What year did the Chevrolet LUV mini truck make its debut?",
            correct_answer: "1972",
            incorrect_answers: ["1982", "1975", "1973"],
        },
        {
            category: "Vehicles",
            type: "boolean",
            difficulty: "hard",
            question: "The term &quot;GTO&quot; was originated by Ferrari?",
            correct_answer: "True",
            incorrect_answers: ["False"],
        },
    ],
    [
        {
            category: "Celebrities",
            type: "multiple",
            difficulty: "easy",
            question: "Which actress married Michael Douglas in 2000?",
            correct_answer: "Catherine Zeta-Jones",
            incorrect_answers: ["Ruth Jones", "Pam Ferris", "Sara Sugarman"],
        },
        {
            category: "Celebrities",
            type: "multiple",
            difficulty: "medium",
            question: "Which of these people is NOT a part of the Internet comedy group Mega64?",
            correct_answer: "Jon Jafari",
            incorrect_answers: ["Rocco Botte", "Derrick Acosta", "Shawn Chatfield"],
        },
        {
            category: "Celebrities",
            type: "multiple",
            difficulty: "medium",
            question: "What was the cause of death for Freddie Mercury?",
            correct_answer: "Pneumonia",
            incorrect_answers: ["Stomach Cancer", "HIV", "Brain Hemorrhage"],
        },
        {
            category: "Celebrities",
            type: "multiple",
            difficulty: "medium",
            question: "If he was still alive, in what year would Elvis Presley celebrate his 100th birthday?",
            correct_answer: "2035",
            incorrect_answers: ["2030", "2040", "2045"],
        },
        {
            category: "Celebrities",
            type: "multiple",
            difficulty: "medium",
            question: "What was the name of Marilyn Monroe&#039;s first husband?",
            correct_answer: "James Dougherty",
            incorrect_answers: ["Joe Dimaggio", "Kirk Douglas", "Arthur Miller"],
        },
    ],
    [
        {
            category: "Entertainment: Books",
            type: "multiple",
            difficulty: "easy",
            question: "Which famous spy novelist wrote the childrens&#039; story &quot;Chitty-Chitty-Bang-Bang&quot;?",
            correct_answer: "Ian Fleming",
            incorrect_answers: ["Joseph Conrad", "John Buchan", "Graham Greene"],
        },
        {
            category: "Entertainment: Books",
            type: "multiple",
            difficulty: "medium",
            question: "Who wrote the children&#039;s story &quot;The Little Match Girl&quot;?",
            correct_answer: "Hans Christian Andersen",
            incorrect_answers: ["Charles Dickens", "Lewis Carroll", "Oscar Wilde"],
        },
        {
            category: "Entertainment: Books",
            type: "multiple",
            difficulty: "easy",
            question: "What&#039;s Harry Potter&#039;s dad&#039;s name?",
            correct_answer: "James Potter",
            incorrect_answers: ["Joey Potter", "Frank Potter", "Hairy Potter Sr."],
        },
        {
            category: "Entertainment: Books",
            type: "multiple",
            difficulty: "hard",
            question: "Where does the book &quot;The Silence of the Lambs&quot; get its title from?",
            correct_answer: "The main character&#039;s trauma in childhood",
            incorrect_answers: [
                "The relation it has with killing the innocents",
                "The villain&#039;s favourite meal",
                "The voice of innocent people being shut by the powerful",
            ],
        },
        {
            category: "Entertainment: Books",
            type: "boolean",
            difficulty: "medium",
            question: "Originally, the character Charlie from Charlie and the Chocolate Factory was going to be black.",
            correct_answer: "True",
            incorrect_answers: ["False"],
        },
    ],
    [
        {
            category: "Science: Mathematics",
            type: "multiple",
            difficulty: "medium",
            question: "What is the area of a circle with a diameter of 20 inches if &pi;= 3.1415?",
            correct_answer: "314.15 Inches",
            incorrect_answers: ["380.1215 Inches", "3141.5 Inches", "1256.6 Inches"],
        },
        {
            category: "Science: Mathematics",
            type: "multiple",
            difficulty: "easy",
            question: "What&#039;s the square root of 49?",
            correct_answer: "7",
            incorrect_answers: ["4", "12", "9"],
        },
        {
            category: "Science: Mathematics",
            type: "boolean",
            difficulty: "medium",
            question: "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
            correct_answer: "True",
            incorrect_answers: ["False"],
        },
        {
            category: "Science: Mathematics",
            type: "boolean",
            difficulty: "medium",
            question: "Zero factorial is equal to zero. ",
            correct_answer: "False",
            incorrect_answers: ["True"],
        },
        {
            category: "Science: Mathematics",
            type: "multiple",
            difficulty: "medium",
            question:
                "In the complex plane, multiplying a given function by i rotates it anti-clockwise by how many degrees?",
            correct_answer: "90",
            incorrect_answers: ["180", "270", "0"],
        },
    ],
    [
        {
            category: "Entertainment: Television",
            type: "multiple",
            difficulty: "easy",
            question: "In Star Trek: The Next Generation, what is the name of Data&#039;s cat?",
            correct_answer: "Spot",
            incorrect_answers: ["Mittens", "Tom", "Kitty"],
        },
        {
            category: "Entertainment: Television",
            type: "multiple",
            difficulty: "easy",
            question:
                "When Donkey Kong died in the &quot;Donkey Kong Country&quot; episode &quot;It&#039;s a Wonderful Life&quot;, who was his guardian angel?",
            correct_answer: "Eddie the Mean Old Yeti",
            incorrect_answers: ["Kiddy Kong", "Diddy Kong", "King K. Rool"],
        },
        {
            category: "Entertainment: Television",
            type: "boolean",
            difficulty: "easy",
            question: "Klingons express emotion in art through opera and poetry.",
            correct_answer: "True",
            incorrect_answers: ["False"],
        },
        {
            category: "Entertainment: Television",
            type: "multiple",
            difficulty: "hard",
            question: "What is the Klingon&#039;s afterlife called?",
            correct_answer: "Sto-vo-kor",
            incorrect_answers: ["Valhalla", "Karon&#039;gahk", "New Jersey"],
        },
        {
            category: "Entertainment: Television",
            type: "multiple",
            difficulty: "easy",
            question:
                "What was the name of the teenage witch played by Melisa Joan Hart who lives with her witch aunts Hilda and Zelda?",
            correct_answer: "Sabrina",
            incorrect_answers: ["Hermione", "Dorothy", "Dahlia"],
        },
    ],
    [
        {
            category: "Entertainment: Board Games",
            type: "boolean",
            difficulty: "easy",
            question: "There is a Donald Trump Board Game, which was made in 1989.",
            correct_answer: "True",
            incorrect_answers: ["False"],
        },
        {
            category: "Entertainment: Board Games",
            type: "multiple",
            difficulty: "hard",
            question: "The board game &quot;Ra&quot; was designed by which designer? ",
            correct_answer: "Reiner Knizia",
            incorrect_answers: ["Bruno Cathala", "Uwe Rosenburg", "Allison Kline"],
        },
        {
            category: "Entertainment: Board Games",
            type: "multiple",
            difficulty: "medium",
            question: "In &quot;Magic: The Gathering&quot;, what instant card has the highest converted mana cost?",
            correct_answer: "Blinkmoth Infusion",
            incorrect_answers: ["Vitalizing Wind", " Chant of Vitu-Ghazi", "Assert Authority"],
        },
        {
            category: "Entertainment: Board Games",
            type: "multiple",
            difficulty: "medium",
            question:
                "In &quot;Magic: The Gathering&quot;, during the design for Planar Chaos, what color did the developers think of adding in as the sixth color?",
            correct_answer: "Purple",
            incorrect_answers: ["Brown", "Pink", "Orange"],
        },
        {
            category: "Entertainment: Board Games",
            type: "multiple",
            difficulty: "hard",
            question: "When Magic: The Gathering was first solicited, which of the following was it originally titled?",
            correct_answer: "Mana Clash",
            incorrect_answers: ["Magic", "Magic Clash", "Mana Duels"],
        },
    ],
];
